[package]
name = "pdfmgr"
version = "0.1.0"
authors = ["amber"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ...

[package.metadata]
# Executable naar ~/.cargo/bin
[install]
prefix = "~/.cargo"
